### ISSUE TITLE
Breaking changes in libsignal-protocol?

### ISSUE THREAD

**Issue by greenbeauty** [whisperfish/libsignal-service-rs#114]
I stumbled on some breaking changes in libsignal-protocol upstream while trying to build gurk-rs, a dependent of libsignal-service-rs.

I worked around the issue by adding the tag 'v0.9.6' to the libsignal-protocol (https://github.com/signalapp/libsignal-client) dependency in my local checkout of libsignal-service-rs.

I've attached the build errors. I don't understand any Rust, so sorry I can't address the error specifically: 
[Hunx2Xq8.txt](https://github.com/whisperfish/libsignal-service-rs/files/7470419/Hunx2Xq8.txt)

**Comment by greenbeauty** [comment]
Maybe it's something to do with this?
https://github.com/signalapp/libsignal-client/commit/64ad39c54d1fef54e90586d50af0574fb2eb16fb

**Comment by rubdos** [comment]
Yep, thanks for reporting this! We'll probably want to pin the libsignal-client versions in Cargo.toml. There's been discussion before about this, and it makes sense to do so.

**Comment by rubdos** [comment]
I think https://github.com/whisperfish/libsignal-service-rs/pull/115  should have resolved this issue.
