### ISSUE TITLE
Don't let users provide rng

### ISSUE THREAD

**Issue by gferon** [whisperfish/libsignal-service-rs#128]
I'm not sure there's any advantage requiring structs to be initialized with a custom rng. We might want to just use `rng::thread_rng()` when we need it. (it's already done like that in a few places, so it would also be a good occasion to clean up)

**Comment by rubdos** [comment]
Hmm. I'm not sure I agree. Supplying a custom random generator might mean that with minimal API-change, we could have signal in a `no_std` environment.

**Comment by gferon** [comment]
Alright that makes sense, I was just thinking about this randomly.
