### ISSUE TITLE
Invalid certificate when using SignalServers::Staging

### ISSUE THREAD

**Issue by hackel** [whisperfish/libsignal-service-rs#131]
I'm not sure if this is already known/intended, but I couldn't get a device link URL without switching to the Production servers.  I get the following error on Staging:
> Service error: Websocket error: error while connecting to websocket: IO error: invalid certificate: UnknownIssuer

I see you have SIGNAL_ROOT_CA hard-coded in the lib, so I thought something might have changed upstream.  Do you do most of your development against the production servers?  Have you tried to use something like [dosco/signal-dev](https://github.com/dosco/signal-dev)?

Edit: I've attached the certificate I downloaded manually from https://chat.staging.signal.org/ and it is indeed different than the one for https://chat.signal.org/ which is the same as the hard-coded one.

[signal-cert.zip](https://github.com/whisperfish/libsignal-service-rs/files/7998086/signal-cert.zip)

**Comment by rubdos** [comment]
It makes sense that both servers use separate certificates. We should indeed patch the library such that it picks the correct cert for both servers.

**Comment by gferon** [comment]
Thanks @hackel and sorry for the delay, this will be fixed when #146 gets merged.
