### ISSUE TITLE
[Question] Is this project already in a useable state?

### ISSUE THREAD

**Issue by netthier** [whisperfish/libsignal-service-rs#15]
Hello,
I wrote a Signal chat bot in Rust, and I'm currently using signal-cli through dbus to do all the backend stuff.
Is this crate in a state, where I could use it in my project? The docs are a bit empty...
Are the following features implemented?
- Sending/Receiving Messages to/from groups and users 
- Sending/Receiving Attachments to/from groups and users
- Registering as a secondary device by taking a tsdevice link
- Registering other devices by providing a tsdevice link
- Reacting to messages
- Deleting messages

Thanks!

**Comment by rubdos** [comment]
> Hello,
> I wrote a Signal chat bot in Rust, and I'm currently using signal-cli through dbus to do all the backend stuff.
> Is this crate in a state, where I could use it in my project? The docs are a bit empty...
> Are the following features implemented?
> 
>     * Sending/Receiving Messages to/from groups and users

Receiving: yes, Sending: no

> 
>     * Sending/Receiving Attachments to/from groups and users

Receiving: yes, Sending: no. There is a lingering bug in reception of attachments though, we're not sure where yet.

>     * Registering as a secondary device by taking a tsdevice link
> 
>     * Registering other devices by providing a tsdevice link

@gferon implemented secondary registration, not 100% sure what's there and what is not.  IIRC, registering as a primary device is implemented at this point.

>     * Reacting to messages

As in, quotes? No, and it's not yet on the radar.

>     * Deleting messages

No, not yet.

If you want, feel free to join us on the #whisperfish:rubdos.be Matrix channel, or on #whisperfish on Freenode, where I am working on a Signal app for SailfishOS, writing the features in here when I need them. Thanks for your interest!

**Comment by gferon** [comment]
Sounds like you need exactly what I'm working on (albeit slowly). 

As @rubdos said, I started to work on secondary device registration but what's currently merged is not enough to start using the crate after linking from your main device. 

I started to draft a plan to re-implement the basic features of signal-cli in pure Rust as an exemple of this crate. Would that help? 

I'll open a Draft PR tomorrow with some basic sketch of what I want to achieve.

**Comment by netthier** [comment]
Thank you both for the replies!
By reactions I meant reacting to a message with an emoji. This is doable on Android by long-tapping a message, and then selecting an emoji.

> I started to draft a plan to re-implement the basic features of signal-cli in pure Rust as an exemple of this crate. Would that help?
Wouldn't that require a working sending implementation though?
Also, I'm not looking for a 1:1 signal-cli replacement, I just want to send and receive messages from Rust. I'm interested in this crate, because my current solution over dbus is very hacky.

I'll port my bot as soon as sending works though!

**Comment by rubdos** [comment]
> By reactions I meant reacting to a message with an emoji. This is doable on Android by long-tapping a message, and then selecting an emoji.

Ah right, I *think* these come through already, but I'm not 100% sure. We don't have the UI in Whisperfish to show them, so currently I just drop them :'/

> > I started to draft a plan to re-implement the basic features of signal-cli in pure Rust as an exemple of this crate. Would that help?
> 
> Wouldn't that require a working sending implementation though?

We're not far off for that though, if I have time this weekend I'd like to take a look at sending.

> Also, I'm not looking for a 1:1 signal-cli replacement, I just want to send and receive messages in Rust. I'm interested in this crate, because my current solution with signal-cli over dbus is very hacky.
> 
> I'll port my bot as soon as sending works though!

Very cool! Since we have multiple people asking for botting-like behaviour, it might be useful to implement a bot crate, that does some of the opinionated stuff (storage and the like) for a bot framework. There's still quite some stuff to manage beyond just this crate.

**Comment by gferon** [comment]
> We're not far off for that though, if I have time this weekend I'd like to take a look at sending.

You need to do the whole setup of pre-keys first. Do you think I should actually create the bot crate that would resemble `signal-cli` instead of an example? I have some `DeviceConfig` struct and was going to implement the storage traits from `libsignal-protocol-rs` to store things into JSON files.

**Comment by gferon** [comment]
Soooo... I've just dumped the current state of my attempt to build a CLI and iron out the parts of the crate that were never used.

I'll keep committing as I go on https://github.com/gferon/libsignal-service-rs/tree/signal-cli, while trying to discuss changes that need to be done in the crate as fast as I can to integrate them in smaller blocks.

@rubdos do you think I should just start my own repo for the `signal-cli-rs` or do you think it's good to have it here?

**Comment by gferon** [comment]
FYI: I have spawned a side-repository to be able to iterate faster with my CLI implementation: http://github.com/gferon/signal-bot-rs.

I'll use it to merge patches upstream to both `libsignal-service-rs` and `libsignal-protocol-rs` when I can.

**Comment by gferon** [comment]
> Any updates on this?

I wasn't able to spend as much time as I wanted to on this in the past few weeks. Still didn't make decrypting messages after registering work, but I already have some good progress and fixed a bunch of bugs with my initial implementation.

I'll try to have a look next week at the state but as far as I remember it felt pretty close.

**Comment by netthier** [comment]
Thanks!

**Comment by gferon** [comment]
Quick status update: receiving (and decrypting) text works now after registering as a secondary device. The code is _really_ gross right now, so I'll focus on cleaning that up, committing what makes sense to [libsignal-protocol-rs](https://github.com/Michael-F-Bryan/libsignal-protocol-rs) and [libsignal-service-rs](https://github.com/Michael-F-Bryan/libsignal-service-rs) and trying to think of the structure of the future bot / `signal-cli` crate.

**Comment by gferon** [comment]
@netthier I'm starting to have a more coherent structure for my wrapper project around `libsignal-service-rs`. Could you have a look at https://github.com/gferon/signal-bot-rs/blob/wip/src/main.rs to see if this kind of API would work for you? (don't bother looking at the internals for now, as I change them all the time). For now, it only supports registering and receiving messages.

@rubdos it's essentially a shitty version of [whisperfish](https://gitlab.com/rubdos/whisperfish) disguised as a Rust library :smile:

**Comment by netthier** [comment]
@gferon That looks awesome! 
The Manager struct seems to be pretty much exactly what I need.
Also, do the v2 groups work? signal-cli does not support them, so our bot group chat is the only one that's still v1.

**Comment by gferon** [comment]
> @gferon That looks awesome!
> The Manager struct seems to be pretty much exactly what I need.
> Also, do the v2 groups work? signal-cli does not support them, so our bot group chat is the only one that's still v1.

I haven't tested yet group v2, but AFAIK it should, yes.

I'll keep improving the new crate, and integrate it with [gurk](https://github.com/boxdot/gurk-rs), which I think should cover everything that you're looking to do. I'll ping you when it's in a ready state for you to contribute back whatever you need on top!

**Comment by gferon** [comment]
@netthier it looks like https://github.com/gferon/signal-bot-rs is starting to look rather good, have a look at the TODO list on the README. You might not be able to use most of the stuff right now because the pull-requests aren't merged, but I can't already confirm that registration, receiving, sending (with emoji reactions) now work well.
