### ISSUE TITLE
 [Feature request] Release on crates.io

### ISSUE THREAD

**Issue by werdahias** [whisperfish/libsignal-service-rs#167]
I intend to package libsignal-service for debian. This would require this crate being on crates.io. I'd appreciate it if you could publish it.

Cheers

**Comment by gferon** [comment]
Thanks for your interest, unfortunately this isn't possible as two of the upstream crates we depend on aren't published on `crates.io` (https://github.com/signalapp/libsignal) and they have already expressed that they do not wish to publish them.

Additionally (and as a side effect), I'm not sure this crate is ready to be published/package since we don't really version it. I'm curious to get the input of @rubdos on that.

**Comment by rubdos** [comment]
> Additionally (and as a side effect), I'm not sure this crate is ready to be published/package since we don't really version it. I'm curious to get the input of @rubdos on that.

I would be fine starting to follow semver. It only really makes sense though, if we're actually publishing it indeed. We're breaking stuff quite often, still.

I'm curiou, @werdahias, where is libsignal-service used that it's actually of interest to have it as a Debian package?

**Comment by werdahias** [comment]
@rubdos  It is used in Flare, an unoffical GTK Signal client.
@gferon  I open an issue in the libsignal repo, it looks like they might consider it.

**Comment by gferon** [comment]
Thanks for filing the issue! I feel like this is too early for both this library and Flare, which relies on https://github.com/whisperfish/presage (that I maintain). Distribution users (especially Debian) expect some sort of stability (not as in never changes) from the software they install from the official repositories, which you probably will struggle to get here.

What about taking it step by step and starting with `crates.io` first, which will already help us publish known functional version of our stack? As for the Debian package, I'm thinking we could add some recipe to publish `.deb` packages on a custom repository, but I would really wait to submit anything to the official repos.

**Comment by Be-ing** [comment]
Correct me if I'm wrong, but IIUC it's not impossible to package non-crates.io crates in Debian, it's just that Debian's Rust packaging tooling assumes crates are on crates.io. Is that correct?

> Thanks for your interest, unfortunately this isn't possible as two of the upstream crates we depend on aren't published on crates.io (https://github.com/signalapp/libsignal) and they have already expressed that they do not wish to publish them.

Considering this, wouldn't you have to start packaging the libsignal crates first?

>  I'm thinking we could add some recipe to publish .deb packages on a custom repository

not sure that's worth the trouble considering Flare already publishes a Flatpak

**Comment by rubdos** [comment]
> What about taking it step by step and starting with `crates.io` first, which will already help us publish known functional version of our stack? As for the Debian package, I'm thinking we could add some recipe to publish `.deb` packages on a custom repository, but I would really wait to submit anything to the official repos.

If we're publishing on crates.io, I don't see why that wouldn't end up on Debian itself. That's totally okay IMO. *If* we publish on crates.io, we'll probably go through a lot of 0.x versions, just like libsignal is doing... If that sounds okay to @werdahias, I think we should just try to do that.

**Comment by werdahias** [comment]
@rubdos  Sure. Note that for an official Debian (ubuntu) package **all** crates that Flare uses have to be packaged beforehand. That's why I opened this issue. In regards to flatpak: Native packages are always better than "containers" like flatpak (imho).

**Comment by Be-ing** [comment]
Then it seems Debian's policies prevent Flare or any other Signal client from being packaged in Debian considering the upstream libraries will not be published to crates.io.

**Comment by werdahias** [comment]
@rubdos  Sure. Note that for an official Debian (ubuntu) package **all** crates that Flare uses have to be packaged beforehand. That's why I opened this issue. In regards to flatpak: Native packages are always better than "containers" like flatpak (imho).

**Comment by gferon** [comment]
I'll close this issue until `libsignal` decides to publish on crates.io, at which stage we'll also publish.
