### ISSUE TITLE
Not sending SyncMessage if only linked device

### ISSUE THREAD

**Issue by Schmiddiii** [whisperfish/libsignal-service-rs#226]
If using Flare (and thus presage + libsignal-service-rs) as the only linked device to Signal Android/IOS, there is no sync message sent to the main device. I suspect that [this line](https://github.com/whisperfish/libsignal-service-rs/blob/main/libsignal-service/src/sender.rs#L357) should also check if the device is a secondary device and then always send a SyncMessage.

This was figured out in the Flare Matrix room, at the bottom of [this thread](https://matrix.to/#/!xgTDfyBMshaGihcEzM:matrix.org/$s_g1J2IyaUATIn_S_j4AT3TbbeF31aKklmRB03ehi5w?via=matrix.org&via=kde.org&via=rubdos.be).

**Comment by rubdos** [comment]
I supposed `sub_device_count` should handle that, but I think you're right. I wonder whether we should (again) change the `get_sub_device_sessions`  semantics, this time to mean: return all device IDs that are not the current device. I'm not sure what Whisperfish takes as semantics there.

**Comment by gferon** [comment]
Is this still a problem, I tested right now and it works fine.

**Comment by Schmiddiii** [comment]
Sorry, I forgot to respond to this issue. I sadly cannot currently check (with the current versions of libsignal-service-rs) if this is still an issue due to the contact sync issue of presage and me not wanting to loose my linked devices that I normally use. I will check again once the contact sync issue of presage is resolved.

**Comment by Schmiddiii** [comment]
Sorry, I forgot to respond to this issue. I sadly cannot currently check (with the current versions of libsignal-service-rs) if this is still an issue due to the contact sync issue of presage and me not wanting to loose my linked devices that I normally use. I will check again once the contact sync issue of presage is resolved.

**Comment by Schmiddiii** [comment]
Should be fixed by #262
