### ISSUE TITLE
Group decryption fails due PNI pending member

### ISSUE THREAD

**Issue by hrdl-github** [whisperfish/libsignal-service-rs#328]
Background: there's a single group that did not show up in gurk until I filtered out errors in https://github.com/whisperfish/libsignal-service-rs/blob/65b51dbe7b42dae992f6a6d4c444bc2081a70be0/libsignal-service/src/groups_v2/operations.rs#L239-L243 . In particular, the group has three pending members. The decryption of one of those fails at https://github.com/whisperfish/libsignal-service-rs/blob/65b51dbe7b42dae992f6a6d4c444bc2081a70be0/libsignal-service/src/groups_v2/operations.rs#L134 with `GroupDecodingError::NotAci`. The group contains around 20 accounts that show up as "Deleted account" in the official client, which might be relevant in this case.

Tested on f99ff8324378ea653dbd5aa0c5d55e4414b34e23.

**Comment by direc85** [comment]
Thanks for reporting!

This is another side effect of not supporting group update messages properly. I guess this bumps up the priority of it. It's been on my list for ages and I even have some code for it...

Related bug: [whisperfish#706](https://gitlab.com/whisperfish/whisperfish/-/issues/706)
