### ISSUE TITLE
Add initial support for groups v2 metadata fetching & decrypting

### ISSUE THREAD

**Issue by gferon** [whisperfish/libsignal-service-rs#70]
TODO (more or less):

* Implement an equivalent of the `PushService` for the new groups v2 endpoints (called `GroupsV2Api` in the Java source code)
* Import new Protobuf models
* Only fetch group participants for now

Use https://github.com/signalapp/zkgroup/ for encrypt/decrypt operations.

**Comment by rubdos** [comment]
@gferon don't we have this at this point?

**Comment by gferon** [comment]
Yes, we do!
